# Using numpy to perform arithmetic operations on data

In [66]:
import numpy as np
from numpy.random import randn

In [67]:
# np.set_printoptions(precision = 2)

## creating arrays

### creating array using list

In [68]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [69]:
arr2 = np.array([[10,20,30],[40,50,60]])
arr2

array([[10, 20, 30],
       [40, 50, 60]])

### Creating arrays via assignment

In [70]:
np.random.seed(25)
arr3 = 36*np.random.randn(6)
arr3

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [71]:
arr4 = np.arange(36)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

### Performing arithimetic on arrays

In [72]:
print("arr1 ",arr1)
print("arr1*10",arr1*10)

arr1  [1 2 3 4 5 6]
arr1*10 [10 20 30 40 50 60]


In [73]:
print(f'array1 {arr1}\n array3 {arr3}')
print(f'array1 + array3 {arr1+arr3}')
arr1 + arr3

array1 [1 2 3 4 5 6]
 array3 [  8.22  36.97 -30.23 -21.28 -34.45  -8.  ]
array1 + array3 [  9.22  38.97 -27.23 -17.28 -29.45  -2.  ]


array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [74]:
arr3 - arr1

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [75]:
arr3 * arr1

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

In [76]:
arr3/arr1

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

# Multiplication of matrices and basic algebra

In [77]:
aa = np.array([[2,4,6],[1,3,5],[10,20,30]])
aa

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [10, 20, 30]])

In [78]:
bb = np.array([[0,1,2],[3,4,5],[6,7,8]])
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
aa*bb
# it only multiplies 
# 1st element of 1st array with 1st element of 2nd array and so on

array([[  0,   4,  12],
       [  3,  12,  25],
       [ 60, 140, 240]])

In [80]:
np.dot(aa,bb)
# True matrix multiplication

array([[ 48,  60,  72],
       [ 39,  48,  57],
       [240, 300, 360]])