# Multiplying matrices

In [7]:
import numpy as np
from numpy.random import randn

In [8]:
np.set_printoptions(precision = 2)

In [9]:
mat1 = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])
mat1

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [10]:
mat2 = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
mat2

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
mat1 * mat2

# general multiplication of of individual elements 
# from mat1 and mat2

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [12]:
np.dot(mat1, mat2)

# it results original matrix multiplication

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])